name: victoria_user
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.5.3
  http: ^1.4.0
  country_code_picker: ^3.3.0
  pinput: ^5.0.1
  image_picker: ^1.1.2
  get: ^4.7.2
  dotted_border: ^2.1.0
  url_launcher: ^6.3.1
  intl: ^0.19.0
  flutter_native_splash: ^2.4.6
  change_app_package_name: ^1.5.0
  slide_to_act: ^2.0.2
  shimmer: ^3.0.0
  permission_handler: ^12.0.1
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/app_images/
    - assets/app_icon/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/app_fonts/Poppins-Black.ttf
        - asset: assets/app_fonts/Poppins-Bold.ttf
        - asset: assets/app_fonts/Poppins-ExtraBold.ttf
        - asset: assets/app_fonts/Poppins-ExtraLight.ttf
        - asset: assets/app_fonts/Poppins-Light.ttf
        - asset: assets/app_fonts/Poppins-Medium.ttf
        - asset: assets/app_fonts/Poppins-Regular.ttf
        - asset: assets/app_fonts/Poppins-SemiBold.ttf
        - asset: assets/app_fonts/Poppins-Thin.ttf
    - family: RethinkSansBold
      fonts:
        - asset: assets/app_fonts/RethinkSans-Bold.ttf
    - family: RethinkSansExtraBold
      fonts:
        - asset: assets/app_fonts/RethinkSans-ExtraBold.ttf
    - family: RethinkSansMedium
      fonts:
        - asset: assets/app_fonts/RethinkSans-Medium.ttf
    - family: RethinkSansRegular
      fonts:
        - asset: assets/app_fonts/RethinkSans-Regular.ttf
    - family: RethinkSansSemiBold
      fonts:
        - asset: assets/app_fonts/RethinkSans-SemiBold.ttf

flutter_native_splash:
  color: "#E9FFEC"
  image: assets/app_images/app-logo.png
  android: true
  ios: true
